<?php
/**
 * Custom Rate Limits Configuration
 * Generated by UserSpice Rate Limiting Dashboard
 * Last updated: 2025-08-08 18:52:06
 */

$rateLimits['login_attempt']['ip_max'] = 20;
$rateLimits['login_attempt']['ip_window'] = 900;
$rateLimits['login_attempt']['user_max'] = 5;
$rateLimits['login_attempt']['user_window'] = 900;
$rateLimits['login_attempt']['total_max'] = 40;
$rateLimits['login_attempt']['total_window'] = 900;

$rateLimits['totp_verify']['ip_max'] = 20;
$rateLimits['totp_verify']['ip_window'] = 600;
$rateLimits['totp_verify']['user_max'] = 10;
$rateLimits['totp_verify']['user_window'] = 600;
$rateLimits['totp_verify']['total_max'] = 40;
$rateLimits['totp_verify']['total_window'] = 600;

$rateLimits['totp_verify_and_activate']['ip_max'] = 20;
$rateLimits['totp_verify_and_activate']['ip_window'] = 600;
$rateLimits['totp_verify_and_activate']['user_max'] = 10;
$rateLimits['totp_verify_and_activate']['user_window'] = 600;
$rateLimits['totp_verify_and_activate']['total_max'] = 40;
$rateLimits['totp_verify_and_activate']['total_window'] = 600;

$rateLimits['totp_regenerate_backup_codes']['ip_max'] = 20;
$rateLimits['totp_regenerate_backup_codes']['ip_window'] = 600;
$rateLimits['totp_regenerate_backup_codes']['user_max'] = 10;
$rateLimits['totp_regenerate_backup_codes']['user_window'] = 600;
$rateLimits['totp_regenerate_backup_codes']['total_max'] = 40;
$rateLimits['totp_regenerate_backup_codes']['total_window'] = 600;

$rateLimits['passkey_register']['ip_max'] = 20;
$rateLimits['passkey_register']['ip_window'] = 600;
$rateLimits['passkey_register']['user_max'] = 10;
$rateLimits['passkey_register']['user_window'] = 600;
$rateLimits['passkey_register']['total_max'] = 40;
$rateLimits['passkey_register']['total_window'] = 600;

$rateLimits['passkey_verify']['ip_max'] = 20;
$rateLimits['passkey_verify']['ip_window'] = 900;
$rateLimits['passkey_verify']['user_max'] = 5;
$rateLimits['passkey_verify']['user_window'] = 900;
$rateLimits['passkey_verify']['credential_max'] = 3;
$rateLimits['passkey_verify']['credential_window'] = 900;
$rateLimits['passkey_verify']['total_max'] = 30;
$rateLimits['passkey_verify']['total_window'] = 900;

$rateLimits['passkey_store']['ip_max'] = 20;
$rateLimits['passkey_store']['ip_window'] = 600;
$rateLimits['passkey_store']['user_max'] = 10;
$rateLimits['passkey_store']['user_window'] = 600;
$rateLimits['passkey_store']['total_max'] = 40;
$rateLimits['passkey_store']['total_window'] = 600;

$rateLimits['password_reset_request']['ip_max'] = 5;
$rateLimits['password_reset_request']['ip_window'] = 3600;
$rateLimits['password_reset_request']['email_max'] = 2;
$rateLimits['password_reset_request']['email_window'] = 3600;
$rateLimits['password_reset_request']['total_max'] = 10;
$rateLimits['password_reset_request']['total_window'] = 3600;

$rateLimits['password_reset_submit']['ip_max'] = 20;
$rateLimits['password_reset_submit']['ip_window'] = 600;
$rateLimits['password_reset_submit']['token_max'] = 5;
$rateLimits['password_reset_submit']['token_window'] = 1800;
$rateLimits['password_reset_submit']['total_max'] = 40;
$rateLimits['password_reset_submit']['total_window'] = 600;

$rateLimits['registration_attempt']['ip_max'] = 5;
$rateLimits['registration_attempt']['ip_window'] = 3600;
$rateLimits['registration_attempt']['total_max'] = 10;
$rateLimits['registration_attempt']['total_window'] = 3600;

$rateLimits['email_verification']['ip_max'] = 20;
$rateLimits['email_verification']['ip_window'] = 600;
$rateLimits['email_verification']['email_max'] = 5;
$rateLimits['email_verification']['email_window'] = 3600;
$rateLimits['email_verification']['total_max'] = 40;
$rateLimits['email_verification']['total_window'] = 600;

$rateLimits['diagnostics']['ip_max'] = 20;
$rateLimits['diagnostics']['ip_window'] = 600;
$rateLimits['diagnostics']['user_max'] = 10;
$rateLimits['diagnostics']['user_window'] = 600;
$rateLimits['diagnostics']['total_max'] = 4443;
$rateLimits['diagnostics']['total_window'] = 600;

