name: userspice_oauth_client_dart_example
description: A Dart command-line example for UserSpice OAuth.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <3.0.0' # Or newer, e.g. '>=2.19.0 <4.0.0' for latest features

dependencies:
  http: ^0.13.0 # Or the latest version of the http package

dev_dependencies:
  lints: ^2.0.0 # Or latest
  test: ^1.16.0 # Or latest
